# Generated by Django 4.1.2 on 2023-05-10 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("descritores", "0003_alter_imagemodel_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageInserted",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="")),
            ],
        ),
    ]
